modLoader="javafml"
loaderVersion="[43,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="trick_update_1_20"
version="2.3.0"
displayName="Trick Update 1.20"
credits="GabrielDja, DJAM Studio"
displayURL="https://gabrieldjalayer.wixsite.com/gabrieldja-gaming-yt"
logoFile="logo.png"
authors="GabrielDja"
description='''
Minecraft Update 1.20!
'''

[[dependencies.trick_update_1_20]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




