
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.gabrieldja.trickupdate.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.gabrieldja.trickupdate.item.WitherSpawnEggItem;
import net.gabrieldja.trickupdate.item.WildArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.WayfinderArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.WardArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.VexArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.TideArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.StructureVoidItem;
import net.gabrieldja.trickupdate.item.SpireArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.SpawnRaftItem;
import net.gabrieldja.trickupdate.item.SpawnCherryBoatItem;
import net.gabrieldja.trickupdate.item.SnowGolemSpawnEggItem;
import net.gabrieldja.trickupdate.item.SnoutArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.SmithingTemplateNetheriteUpgradeItem;
import net.gabrieldja.trickupdate.item.ShaperArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.SentryArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.RibArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.RaiserArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.PotteryShardSkullItem;
import net.gabrieldja.trickupdate.item.PotteryShardPrizeItem;
import net.gabrieldja.trickupdate.item.PotteryShardArmsUpItem;
import net.gabrieldja.trickupdate.item.PotteryShardArcherItem;
import net.gabrieldja.trickupdate.item.NetheriteArmorAmethystCoastItem;
import net.gabrieldja.trickupdate.item.MusicDiscRelicItem;
import net.gabrieldja.trickupdate.item.LigthBlockItem;
import net.gabrieldja.trickupdate.item.IronGolemSpawnEggItem;
import net.gabrieldja.trickupdate.item.IronArmorAmethystCoastItem;
import net.gabrieldja.trickupdate.item.HostArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.GoldArmorAmethystCoastItem;
import net.gabrieldja.trickupdate.item.EyeArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.EnderDragonSpawnEggItem;
import net.gabrieldja.trickupdate.item.DuneArmorTrimSmithingTemplateItem;
import net.gabrieldja.trickupdate.item.DiamondArmorAmethystCoastItem;
import net.gabrieldja.trickupdate.item.DebugStickItem;
import net.gabrieldja.trickupdate.item.CoastArmorTrimItem;
import net.gabrieldja.trickupdate.item.BrushItem;
import net.gabrieldja.trickupdate.item.BarrierItem;
import net.gabrieldja.trickupdate.TrickUpdate120Mod;

public class TrickUpdate120ModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, TrickUpdate120Mod.MODID);
	public static final RegistryObject<Item> BAMBOO_DOOR = doubleBlock(TrickUpdate120ModBlocks.BAMBOO_DOOR, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BLOCK_OF_BAMBOO = block(TrickUpdate120ModBlocks.BLOCK_OF_BAMBOO, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> STRIPPED_BLOCK_OF_BAMBOO = block(TrickUpdate120ModBlocks.STRIPPED_BLOCK_OF_BAMBOO, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BAMBOO_PLANKS = block(TrickUpdate120ModBlocks.BAMBOO_PLANKS, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BAMBOO_MOSAIC = block(TrickUpdate120ModBlocks.BAMBOO_MOSAIC, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BAMBOO_STAIR = block(TrickUpdate120ModBlocks.BAMBOO_STAIR, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BAMBOO_MOSAIC_STAIR = block(TrickUpdate120ModBlocks.BAMBOO_MOSAIC_STAIR, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BAMBOO_SLAB = block(TrickUpdate120ModBlocks.BAMBOO_SLAB, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BAMBOO_MOSAIC_SLAB = block(TrickUpdate120ModBlocks.BAMBOO_MOSAIC_SLAB, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BAMBOO_TRAPDOOR = block(TrickUpdate120ModBlocks.BAMBOO_TRAPDOOR, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BAMBOO_FENCE = block(TrickUpdate120ModBlocks.BAMBOO_FENCE, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BAMBOO_FENCE_GATE = block(TrickUpdate120ModBlocks.BAMBOO_FENCE_GATE, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BAMBOO_PRESSURE_PLATE = block(TrickUpdate120ModBlocks.BAMBOO_PRESSURE_PLATE, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BAMBOO_BUTTON = block(TrickUpdate120ModBlocks.BAMBOO_BUTTON, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> CHERRY_LOG = block(TrickUpdate120ModBlocks.CHERRY_LOG, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> CHERRY_PLANKS = block(TrickUpdate120ModBlocks.CHERRY_PLANKS, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> CHERRY_LEAVES = block(TrickUpdate120ModBlocks.CHERRY_LEAVES, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> CHERRY_SAPLING = block(TrickUpdate120ModBlocks.CHERRY_SAPLING, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> CHERRY_WOOD = block(TrickUpdate120ModBlocks.CHERRY_WOOD, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> DOOR_CHERRY = doubleBlock(TrickUpdate120ModBlocks.DOOR_CHERRY, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> CHERRY_STAIRS = block(TrickUpdate120ModBlocks.CHERRY_STAIRS, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> CHERRY_SLAB = block(TrickUpdate120ModBlocks.CHERRY_SLAB, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> CHERRY_TRAPDOOR = block(TrickUpdate120ModBlocks.CHERRY_TRAPDOOR, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> FENCE_CHERRY = block(TrickUpdate120ModBlocks.FENCE_CHERRY, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> FENCE_GATE_CHERRY = block(TrickUpdate120ModBlocks.FENCE_GATE_CHERRY, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> PRESSURE_PLATE_CHERRY = block(TrickUpdate120ModBlocks.PRESSURE_PLATE_CHERRY, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> CHERRY_BUTTONS = block(TrickUpdate120ModBlocks.CHERRY_BUTTONS, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> CHISELED_BOOKSHELF = block(TrickUpdate120ModBlocks.CHISELED_BOOKSHELF, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> HANGING_SIGN_OAK = block(TrickUpdate120ModBlocks.HANGING_SIGN_OAK, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> HANGING_SIGN_SPRUCE = block(TrickUpdate120ModBlocks.HANGING_SIGN_SPRUCE, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> HANGING_SIGN_DARK_OAK = block(TrickUpdate120ModBlocks.HANGING_SIGN_DARK_OAK, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> HANGING_SIGN_MANGROVE = block(TrickUpdate120ModBlocks.HANGING_SIGN_MANGROVE, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> HANGING_SIGN_ACACIA = block(TrickUpdate120ModBlocks.HANGING_SIGN_ACACIA, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> HANGING_SIGN_BAMBOO = block(TrickUpdate120ModBlocks.HANGING_SIGN_BAMBOO, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> HANGING_SIGN_BIRCH = block(TrickUpdate120ModBlocks.HANGING_SIGN_BIRCH, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> HANGING_SIGN_JUNGLE = block(TrickUpdate120ModBlocks.HANGING_SIGN_JUNGLE, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> HANGING_SIGN_CRIMSON = block(TrickUpdate120ModBlocks.HANGING_SIGN_CRIMSON, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> HANGING_SIGN_WARPED = block(TrickUpdate120ModBlocks.HANGING_SIGN_WARPED, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> HANGING_SIGN_CHERRY = block(TrickUpdate120ModBlocks.HANGING_SIGN_CHERRY, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> SPAWN_RAFT = REGISTRY.register("spawn_raft", () -> new SpawnRaftItem());
	public static final RegistryObject<Item> SPAWN_CHERRY_BOAT = REGISTRY.register("spawn_cherry_boat", () -> new SpawnCherryBoatItem());
	public static final RegistryObject<Item> IRON_GOLEM_SPAWN_EGG = REGISTRY.register("iron_golem_spawn_egg", () -> new IronGolemSpawnEggItem());
	public static final RegistryObject<Item> SNOW_GOLEM_SPAWN_EGG = REGISTRY.register("snow_golem_spawn_egg", () -> new SnowGolemSpawnEggItem());
	public static final RegistryObject<Item> SMITHING_TEMPLATE_NETHERITE_UPGRADE = REGISTRY.register("smithing_template_netherite_upgrade", () -> new SmithingTemplateNetheriteUpgradeItem());
	public static final RegistryObject<Item> COAST_ARMOR_TRIM = REGISTRY.register("coast_armor_trim", () -> new CoastArmorTrimItem());
	public static final RegistryObject<Item> COMMAND_BLOCK = block(TrickUpdate120ModBlocks.COMMAND_BLOCK, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> CHAIN_COMMAND_BLOCK = block(TrickUpdate120ModBlocks.CHAIN_COMMAND_BLOCK, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> REPEATING_COMMAND_BLOCK = block(TrickUpdate120ModBlocks.REPEATING_COMMAND_BLOCK, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> STRUCTURE_BLOCK = block(TrickUpdate120ModBlocks.STRUCTURE_BLOCK, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BARRIER = REGISTRY.register("barrier", () -> new BarrierItem());
	public static final RegistryObject<Item> STRUCTURE_VOID = REGISTRY.register("structure_void", () -> new StructureVoidItem());
	public static final RegistryObject<Item> LIGTH_BLOCK = REGISTRY.register("ligth_block", () -> new LigthBlockItem());
	public static final RegistryObject<Item> DEBUG_STICK = REGISTRY.register("debug_stick", () -> new DebugStickItem());
	public static final RegistryObject<Item> WITHER_SPAWN_EGG = REGISTRY.register("wither_spawn_egg", () -> new WitherSpawnEggItem());
	public static final RegistryObject<Item> ENDER_DRAGON_SPAWN_EGG = REGISTRY.register("ender_dragon_spawn_egg", () -> new EnderDragonSpawnEggItem());
	public static final RegistryObject<Item> IRON_ARMOR_AMETHYST_COAST_HELMET = REGISTRY.register("iron_armor_amethyst_coast_helmet", () -> new IronArmorAmethystCoastItem.Helmet());
	public static final RegistryObject<Item> IRON_ARMOR_AMETHYST_COAST_CHESTPLATE = REGISTRY.register("iron_armor_amethyst_coast_chestplate", () -> new IronArmorAmethystCoastItem.Chestplate());
	public static final RegistryObject<Item> IRON_ARMOR_AMETHYST_COAST_LEGGINGS = REGISTRY.register("iron_armor_amethyst_coast_leggings", () -> new IronArmorAmethystCoastItem.Leggings());
	public static final RegistryObject<Item> IRON_ARMOR_AMETHYST_COAST_BOOTS = REGISTRY.register("iron_armor_amethyst_coast_boots", () -> new IronArmorAmethystCoastItem.Boots());
	public static final RegistryObject<Item> GOLD_ARMOR_AMETHYST_COAST_HELMET = REGISTRY.register("gold_armor_amethyst_coast_helmet", () -> new GoldArmorAmethystCoastItem.Helmet());
	public static final RegistryObject<Item> GOLD_ARMOR_AMETHYST_COAST_CHESTPLATE = REGISTRY.register("gold_armor_amethyst_coast_chestplate", () -> new GoldArmorAmethystCoastItem.Chestplate());
	public static final RegistryObject<Item> GOLD_ARMOR_AMETHYST_COAST_LEGGINGS = REGISTRY.register("gold_armor_amethyst_coast_leggings", () -> new GoldArmorAmethystCoastItem.Leggings());
	public static final RegistryObject<Item> GOLD_ARMOR_AMETHYST_COAST_BOOTS = REGISTRY.register("gold_armor_amethyst_coast_boots", () -> new GoldArmorAmethystCoastItem.Boots());
	public static final RegistryObject<Item> DIAMOND_ARMOR_AMETHYST_COAST_HELMET = REGISTRY.register("diamond_armor_amethyst_coast_helmet", () -> new DiamondArmorAmethystCoastItem.Helmet());
	public static final RegistryObject<Item> DIAMOND_ARMOR_AMETHYST_COAST_CHESTPLATE = REGISTRY.register("diamond_armor_amethyst_coast_chestplate", () -> new DiamondArmorAmethystCoastItem.Chestplate());
	public static final RegistryObject<Item> DIAMOND_ARMOR_AMETHYST_COAST_LEGGINGS = REGISTRY.register("diamond_armor_amethyst_coast_leggings", () -> new DiamondArmorAmethystCoastItem.Leggings());
	public static final RegistryObject<Item> DIAMOND_ARMOR_AMETHYST_COAST_BOOTS = REGISTRY.register("diamond_armor_amethyst_coast_boots", () -> new DiamondArmorAmethystCoastItem.Boots());
	public static final RegistryObject<Item> NETHERITE_ARMOR_AMETHYST_COAST_HELMET = REGISTRY.register("netherite_armor_amethyst_coast_helmet", () -> new NetheriteArmorAmethystCoastItem.Helmet());
	public static final RegistryObject<Item> NETHERITE_ARMOR_AMETHYST_COAST_CHESTPLATE = REGISTRY.register("netherite_armor_amethyst_coast_chestplate", () -> new NetheriteArmorAmethystCoastItem.Chestplate());
	public static final RegistryObject<Item> NETHERITE_ARMOR_AMETHYST_COAST_LEGGINGS = REGISTRY.register("netherite_armor_amethyst_coast_leggings", () -> new NetheriteArmorAmethystCoastItem.Leggings());
	public static final RegistryObject<Item> NETHERITE_ARMOR_AMETHYST_COAST_BOOTS = REGISTRY.register("netherite_armor_amethyst_coast_boots", () -> new NetheriteArmorAmethystCoastItem.Boots());
	public static final RegistryObject<Item> DECORATED_POT = block(TrickUpdate120ModBlocks.DECORATED_POT, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> BRUSH = REGISTRY.register("brush", () -> new BrushItem());
	public static final RegistryObject<Item> SUSPICIOUS_SAND_STAGE_0 = block(TrickUpdate120ModBlocks.SUSPICIOUS_SAND_STAGE_0, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> SUSPICIOUS_SAND_STAGE_1 = block(TrickUpdate120ModBlocks.SUSPICIOUS_SAND_STAGE_1, null);
	public static final RegistryObject<Item> SUSPICIOUS_SAND_STAGE_2 = block(TrickUpdate120ModBlocks.SUSPICIOUS_SAND_STAGE_2, null);
	public static final RegistryObject<Item> SUSPICIOUS_SAND_STAGE_3 = block(TrickUpdate120ModBlocks.SUSPICIOUS_SAND_STAGE_3, null);
	public static final RegistryObject<Item> TORCHFLOWER = block(TrickUpdate120ModBlocks.TORCHFLOWER, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> POTTERY_SHARD_ARCHER = REGISTRY.register("pottery_shard_archer", () -> new PotteryShardArcherItem());
	public static final RegistryObject<Item> POTTERY_SHARD_ARMS_UP = REGISTRY.register("pottery_shard_arms_up", () -> new PotteryShardArmsUpItem());
	public static final RegistryObject<Item> POTTERY_SHARD_PRIZE = REGISTRY.register("pottery_shard_prize", () -> new PotteryShardPrizeItem());
	public static final RegistryObject<Item> POTTERY_SHARD_SKULL = REGISTRY.register("pottery_shard_skull", () -> new PotteryShardSkullItem());
	public static final RegistryObject<Item> PINK_PETALS_STAGE_1 = block(TrickUpdate120ModBlocks.PINK_PETALS_STAGE_1, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> PINK_PETALS_STAGE_2 = block(TrickUpdate120ModBlocks.PINK_PETALS_STAGE_2, null);
	public static final RegistryObject<Item> PINK_PETALS_STAGE_3 = block(TrickUpdate120ModBlocks.PINK_PETALS_STAGE_3, null);
	public static final RegistryObject<Item> PINK_PETALS_STAGE_4 = block(TrickUpdate120ModBlocks.PINK_PETALS_STAGE_4, null);
	public static final RegistryObject<Item> PITCHER_POD_STAGE_0 = block(TrickUpdate120ModBlocks.PITCHER_POD_STAGE_0, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> PITCHER_POD_STAGE_1 = block(TrickUpdate120ModBlocks.PITCHER_POD_STAGE_1, null);
	public static final RegistryObject<Item> PITCHER_POD_STAGE_2 = block(TrickUpdate120ModBlocks.PITCHER_POD_STAGE_2, null);
	public static final RegistryObject<Item> PITCHER_POD_STAGE_3 = block(TrickUpdate120ModBlocks.PITCHER_POD_STAGE_3, null);
	public static final RegistryObject<Item> PITCHER_POD_STAGE_4 = block(TrickUpdate120ModBlocks.PITCHER_POD_STAGE_4, null);
	public static final RegistryObject<Item> PITCHER_PLANT = block(TrickUpdate120ModBlocks.PITCHER_PLANT, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> CALIBRATED_SCULK_SENSOR_INACTIVE = block(TrickUpdate120ModBlocks.CALIBRATED_SCULK_SENSOR_INACTIVE, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> CALIBRATED_SCULK_SENSOR_ACTIVE = block(TrickUpdate120ModBlocks.CALIBRATED_SCULK_SENSOR_ACTIVE, null);
	public static final RegistryObject<Item> SUSPICIOUS_GRAVEL_STAGE_0 = block(TrickUpdate120ModBlocks.SUSPICIOUS_GRAVEL_STAGE_0, TrickUpdate120ModTabs.TAB_TRICK_UPDATE_120);
	public static final RegistryObject<Item> SUSPICIOUS_GRAVEL_STAGE_1 = block(TrickUpdate120ModBlocks.SUSPICIOUS_GRAVEL_STAGE_1, null);
	public static final RegistryObject<Item> SUSPICIOUS_GRAVEL_STAGE_2 = block(TrickUpdate120ModBlocks.SUSPICIOUS_GRAVEL_STAGE_2, null);
	public static final RegistryObject<Item> SUSPICIOUS_GRAVEL_STAGE_3 = block(TrickUpdate120ModBlocks.SUSPICIOUS_GRAVEL_STAGE_3, null);
	public static final RegistryObject<Item> DUNE_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("dune_armor_trim_smithing_template", () -> new DuneArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> EYE_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("eye_armor_trim_smithing_template", () -> new EyeArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> RIB_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("rib_armor_trim_smithing_template", () -> new RibArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("sentry_armor_trim_smithing_template", () -> new SentryArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("snout_armor_trim_smithing_template", () -> new SnoutArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("spire_armor_trim_smithing_template", () -> new SpireArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> TIDE_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("tide_armor_trim_smithing_template", () -> new TideArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> VEX_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("vex_armor_trim_smithing_template", () -> new VexArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> WARD_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("ward_armor_trim_smithing_template", () -> new WardArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> WILD_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("wild_armor_trim_smithing_template", () -> new WildArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> HOST_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("host_armor_trim_smithing_template", () -> new HostArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> RAISER_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("raiser_armor_trim_smithing_template", () -> new RaiserArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("shaper_armor_trim_smithing_template", () -> new ShaperArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE = REGISTRY.register("wayfinder_armor_trim_smithing_template", () -> new WayfinderArmorTrimSmithingTemplateItem());
	public static final RegistryObject<Item> MUSIC_DISC_RELIC = REGISTRY.register("music_disc_relic", () -> new MusicDiscRelicItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
